config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :installs 
  resources :posts
  root 'posts#index'

  

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :image, presence: true

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :edit, :update, :destroy]  
def index
@posts=Post.all
end

def new
@post=Post.new
end

def create
if @post = Post.create(post_params)
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
end

def show  
  
end  

def edit  
  
end  

def update  
  
  if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to post_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
end  

def destroy
	
	@post.destroy
	redirect_to posts_path
end


private

def post_params  
  params.require(:post).permit(:image, :caption)
end 

 def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)  
  { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }[flash_type.to_sym] || flash_type.to_s
end  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<nav class="navbar navbar-default">
  <div class="navbar-container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Pictogram", root_path %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "New Post", new_post_path %>
        </li>
        <li>
          <%= link_to "Login", '#' %>
        </li>
        <li>
          <%= link_to "Register", '#' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<head>
  <title>Pictogram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>
  <%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
   </div>
  <%= render 'form' %>
    <div class="text-center edit-links">
      <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    |
    <%= link_to "Cancel", posts_path %>
   </div>
  

app/views/posts/index.html.erb
<div class="posts-wrapper row">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post-head">
        <div class="name">
          Picture <%= post.id%>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <p class="caption">
        <%= post.caption %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        Image <%= @post.id%>
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.caption %>
    </p>
    <div class="text-center edit-links">
     <%= link_to "Cancel", posts_path %>
    |
     <%= link_to "Edit Post", edit_post_path(@post) %>
    </div>
  
    <div class="text-center">
      <%= link_to "Cancel", posts_path %>
    </div>
  </div>
</div>